### ISSUE TITLE
Helsinki lähtöpaikkana ei palauta määränpääksi Tamperetta tai Lahtea

### ISSUE THREAD

**Issue by anttimie** [joonasronn/JSJuna#1]
Välillä haku toimii ja välillä ei.  Haun logiikassa perustavanlaatuinen bugi?

**Comment by anttimie** [comment]
Branch: devantti lokaalissa
Ongelma: Rivi 13 XMLHTTPReq. alustus väärin, sama myös rivillä 133.

**Comment by aarni-k** [comment]
Kontiomäet, rovaniemet ja muut löytyy vielä tässä.
![image](https://user-images.githubusercontent.com/47100027/52050729-1f10f480-255a-11e9-90ca-33726cdd7bfe.png)
